# Generated by Django 5.0.7 on 2024-08-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
