# Generated by Django 5.0.7 on 2025-06-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlepost",
            name="title",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
